# Generated by Django 2.0.1 on 2018-05-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
